# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='tags',
            field=models.ManyToManyField(to='pins.Tag'),
        ),
    ]
