# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 09:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20161025_1909'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Board')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pins.Pin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.RemoveField(
            model_name='pinaction',
            name='board',
        ),
        migrations.RemoveField(
            model_name='pinaction',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='pinaction',
            name='pinned_by',
        ),
        migrations.DeleteModel(
            name='PinAction',
        ),
    ]
