# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_auto_20161026_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='hash',
            field=models.CharField(default='yo', max_length=40),
            preserve_default=False,
        ),
    ]
