# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 17:15
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=accounts.models.upload_location),
        ),
    ]
