# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='username'),
        ),
    ]
