# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20161020_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default='Shituser', max_length=40, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
