# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 16:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20161022_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='board',
        ),
        migrations.AlterModelOptions(
            name='boardfollower',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='boardfollower',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_followers', to='boards.Board'),
        ),
        migrations.AlterField(
            model_name='boardfollower',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_board_followings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
